### ISSUE TITLE
16.1.4 Crashes my app

### ISSUE THREAD

**Issue by kitenium** [appcelerator-modules/ti.playservices#23]
16.1.3 was running just fine but once I installed 16.1.4 the app crashes immediately on startup

**Comment by kitenium** [comment]
Turns out removing the play-services-ads-lite-17.2.0.aar fixes the issue.

**Comment by hansemannn** [comment]
cc @ypbnv, maybe a regression in the latest version published?

**Comment by ypbnv** [comment]
@kitenium Would you be able to share if you are using any other modules in combination with ti.playservices?

@hansemannn The latest update is effectively only adding the play-services-ads-lite.aar into the module. I suppose this could introduce some ambiguous dependencies if used with other modules built against an older version of the ti.playservices.

**Comment by m1ga** [comment]
@kitenium can you please check your `adb logcat` for
```
05-20 22:21:08.841 24349 24349 E AndroidRuntime: Process: com.miga.testfirebase, PID: 24349
05-20 22:21:08.841 24349 24349 E AndroidRuntime: java.lang.RuntimeException: Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.IllegalStateException: 
05-20 22:21:08.841 24349 24349 E AndroidRuntime: 
05-20 22:21:08.841 24349 24349 E AndroidRuntime: ******************************************************************************
05-20 22:21:08.841 24349 24349 E AndroidRuntime: * The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    *
05-20 22:21:08.841 24349 24349 E AndroidRuntime: * should follow the instructions here: https://goo.gl/fQ2neu to add a valid  *
05-20 22:21:08.841 24349 24349 E AndroidRuntime: * App ID inside the AndroidManifest. Google Ad Manager publishers should     *
05-20 22:21:08.841 24349 24349 E AndroidRuntime: * follow instructions here: https://goo.gl/h17b6x.                           *
05-20 22:21:08.841 24349 24349 E AndroidRuntime: ******************************************************************************
05-20 22:21:08.841 24349 24349 E AndroidRuntime: 
05-20 22:21:08.841 24349 24349 E AndroidRuntime: 
05-20 22:21:08.841 24349 24349 E AndroidRuntime:        at android.app.ActivityThread.installProvider(ActivityThread.java:6144)
05-20 22:21:08.841 24349 24349 E AndroidRuntime:        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5704)
05-20 22:21:08.841 24349 24349 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5643)
05-20 22:21:08.841 24349 24349 E AndroidRuntime:        at android.app.ActivityThread.-wrap2(ActivityThread.java)
05-20 22:21:08.841 24349 24349 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1573)
05-20 22:21:08.841 24349 24349 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
05-20 22:21:08.841 24349 24349 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:173)
05-20 22:21:08.841 24349 24349 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6459)
05-20 22:21:08.841 24349 24349 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
05-20 22:21:08.841 24349 24349 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:938)
05-20 22:21:08.841 24349 24349 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:828)
05-20 22:21:08.841 24349 24349 E AndroidRuntime: Caused by: java.lang.IllegalStateException: 
```
this is the crashlog I have when I use `16.1.4`. The old version is working fine for me too.

**Comment by kitenium** [comment]
@m1ga I see. Thanks for the confirmation. Titanium does not provide this level of details on the crash. It seems like a configuration issue to me. But would be nice to be able to opt out on the ads stuff since most people like me won't be using it.

**Comment by m1ga** [comment]
@kitenium I'm using Titanium too :) You can just run `adb logcat` with an attached device to see the full android log.

**Comment by kitenium** [comment]
@m1ga Yes, I know you. You have forked/created a lot of titanium modules projects.

Actually, I am using one of them in our project thanks to your contribution - tintimage!

Good to know about the adb logcat trick. I am starting to use it from now on.

**Comment by hansemannn** [comment]
Can someone please either fix 16.1.4 or revert to 16.1.3 completely? We tried to use it as well and it crashes the app just after adding it to the tiapp.xml. We are using 16.1.3 for now.

**Comment by anik786** [comment]
16.1.5 solves the crash issue for me, but have new issues with `ti.map`: https://jira.appcelerator.org/browse/AC-6438

Still have to stay on 16.1.3
